version: '3.8'

services:
  # Frontend development service
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules_frontend:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend-dev
    networks:
      - portfolio-dev-network
    stdin_open: true
    tty: true
    command: npm run dev

  # Backend development service
  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - node_modules_backend:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - ./server/.env
    networks:
      - portfolio-dev-network
    stdin_open: true
    tty: true
    command: npm run dev

networks:
  portfolio-dev-network:
    driver: bridge

volumes:
  node_modules_frontend:
  node_modules_backend:
